--- /data/data/com.termux/files/home/ValeraC/Makefile	2022-08-10 15:46:54.281296094 +0900
+++ Makefile	2022-09-15 17:45:05.715143756 +0900
@@ -1,35 +1,11 @@
+LD = "ld.lld"
+LDFLAGS = " -nostdlib -T link.ld -o"
+CC = clang
+CFLAGS = -target i386-pc-none-elf -Wno-unused-command-line-argument \
+		 -mno-sse -mno-avx -O0 -ffreestanding -I ../../include/ -c
+
 all: libvalera.so
 
 libvalera.so:
 	@echo "Compiling Valera shared library..."
-	@gcc valera.c -Wall -shared -o libvalera.so
-
-example:
-	@echo "Compiling example..."
-	@gcc valera.c examples/example.c -I. -o ./example
-	@echo "Run program with ./example"
-
-json:
-	@echo "Compiling json..."
-	@gcc valera.c examples/json-example.c -I. -o ./json
-	@echo "Run program with ./json"
-
-simple:
-	@echo "Compiling simple..."
-	@gcc valera.c examples/simple.c -I. -o ./simple
-	@echo "Run program with ./simple"
-
-join:
-	@echo "Compiling join..."
-	@gcc valera.c examples/join.c -I. -o ./join
-	@echo "Run program with ./join"
-
-test_change:
-	@gcc valera.c examples/test_change.c -I. -o ./change
-
-install: libvalera.so
-	install libvalera.so $(PREFIX)/lib/
-	install valera.h $(PREFIX)/include
-	@echo "================================="
-	@echo "| Valera installed succesfully! |"
-	@echo "================================="
+	$(CC) valera.c $(CFLAGS) -o libvalera.lib
